name: Questionnaire
description: Help us understand your experience.
title: Developer Questionnaire
labels: ['feedback', 'survey']
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the Developer Questionnaire!
        Please answer the following questions to help us improve our platform.

  - type: dropdown
    id: experience
    attributes:
      label: What is your experience level with Arweave development?
      options:
        - Beginner
        - Intermediate
        - Advanced
      required: true

  - type: dropdown
    id: features
    attributes:
      label: Which features of AO are you most interested in?
      options:
        - Data Storage
        - Smart Contracts
        - Ecosystem Collaboration
      required: true

  - type: textarea
    id: comments
    attributes:
      label: Any additional comments?
      placeholder: Share your thoughts here.
